'PlantUML Online Editor: https://www.planttext.com/

@startuml

'!include https://raw.githubusercontent.com/dmitrvk/plantuml/main/base.puml
!include base.puml

class Class {
  +field
  -field
  +method()
  -method()
}

interface Interface {
  +method()
}

Interface <|.. Class

() I

actor Actor
database Database
component Component
cloud Cloud
package Package

@enduml
