skinparam dpi 150
skinparam monochrome true
skinparam style strictuml

skinparam defaultFontName Roboto

skinparam activityBackgroundColor white
skinparam activityDiamondBackgroundColor white
skinparam actorBackgroundColor white
skinparam classAttributeIconSize 0
skinparam classBackgroundColor white
skinparam cloudBackgroundColor white
skinparam componentBackgroundColor white
skinparam databaseBackgroundColor white
skinparam fileBackgroundColor white
skinparam interfaceBackgroundColor white
skinparam genericDisplay old
skinparam noteBackgroundColor white
skinparam packageBackgroundColor white
skinparam participantBackgroundColor white
skinparam usecaseBackgroundColor white

hide empty members

allowmixing

<style>
  arrow {
    LineThickness 1
  }
  classDiagram {
    class {
      header {
        FontStyle bold
      }
    }
  }
  jsonDiagram {
    BackGroundColor White
    LineThickness 1
    RoundCorner 0

    highlight {
      BackGroundColor LightGray
    }
  }
  package {
    LineThickness 1
  }
  wbsDiagram {
    BackgroundColor White
    LineThickness 1
  }
</style>
