@startuml

!theme bw from https://raw.githubusercontent.com/dmitrvk/plantuml-black-and-white/main

autonumber

actor actor
boundary boundary
collections collections
control control
database database
entity entity
participant participant
queue queue

actor -> database : text
actor <-- participant

@enduml
